### PR TITLE
provide unique USB serial number

### PR DESCRIPTION
**Pull request by Ho-Ro**
inspired by https://github.com/erikkaashoek/tinySA/issues/85 create a 12 char string based on the Arduino algorithm https://github.com/limbongofficial/STM32_Core-Arduino/blob/master/cores/arduino/stm32/usb/usbd_desc.c#L326-L370

### CODE REVIEW

**Comment by DiSlord** [comment]
Most good solution generate Serial number on ask inside USB driver (not need ~huge buffer in RAM)
also for generation better use plot_printf:
plot_printf(buf, "%04x%08x", (*(uint32_t *)0x1FFFF7AC + *(uint32_t *)0x1FFFF7B4)&0xFFFF, *(uint32_t *)0x1FFFF7B0);

or use any function for convert digit to different radix (in your solution used radix = 16 for hex)

**Comment by DiSlord** [comment]
usb serial string ID is here:
```
/*
 * USB Device Descriptor.
 */
static const uint8_t vcom_device_descriptor_data[18] = {
  USB_DESC_DEVICE       (0x0110,        /* bcdUSB (1.1).                    */
                         0x02,          /* bDeviceClass (CDC).              */
                         0x00,          /* bDeviceSubClass.                 */
                         0x00,          /* bDeviceProtocol.                 */
                         0x40,          /* bMaxPacketSize.                  */
                         0x0483,        /* idVendor (ST).                   */
                         0x5740,        /* idProduct.                       */
                         0x0200,        /* bcdDevice.                       */
                         1,             /* iManufacturer.                   */
                         2,             /* iProduct.                        */
                         **3,             /* iSerialNumber.                   */**  <<--here is string ID
                         1)             /* bNumConfigurations.              */
};
```
after host ask this string and deivce process it in:
device_handler (ask USB_REQ_GET_DESCRIPTOR)
function call
```
get_descriptor from 
const USBConfig usbcfg = {
  usb_event,
  **get_descriptor,**
  sduRequestsHook,
  sof_handler
};

/*
 * Handles the GET_DESCRIPTOR callback. All required descriptors must be
 * handled here.
 */
static const USBDescriptor *get_descriptor(USBDriver *usbp,
                                           uint8_t dtype,
                                           uint8_t dindex,
                                           uint16_t lang) {

  (void)usbp;
  (void)lang;
  switch (dtype) {
  case USB_DESCRIPTOR_DEVICE:
    return &vcom_device_descriptor;
  case USB_DESCRIPTOR_CONFIGURATION:
    return &vcom_configuration_descriptor;
  case USB_DESCRIPTOR_STRING:
    if (dindex < 4)
      return &vcom_strings[dindex];
  }
  return NULL;
}
```
dindex = 3 is ask serial string, you can use lcd_spi buffer (end) for generate serial and send

**Comment by Ho-Ro** [comment]
Good hint, please check my latest commit.
I did not use printf because the usb strings are using utf-16 wchar, so I do it step by step.

**Comment by DiSlord** [comment]
I add https://github.com/DiSlord/NanoVNA-D/commit/d5377c3c8232fbaf71ad4aad7fabb48125037d53
USB UID optional (selected in CONFIG->EXPERT SETTINGS->USB DEVICE UID

**Comment by Ho-Ro** [comment]
In the next lines you use two times `id1` and do not use `id0 += id2`!

```c
  uint32_t id0 = *(uint32_t *)0x1FFFF7AC; // MCU id0 address
  uint32_t id1 = *(uint32_t *)0x1FFFF7B0; // MCU id1 address
  uint32_t id2 = *(uint32_t *)0x1FFFF7B4; // MCU id2 address
  uint64_t uid = id1;
  id0+= id2;
  uid = id1 | (uid<<32);                  // generate unique 64bit ID
```

**Comment by DiSlord** [comment]
Thanks, fixed https://github.com/DiSlord/NanoVNA-D/commit/9f35ce5a7ce0fa606134ed9502f543815552c879

**Comment by DiSlord** [comment]
About LTO, yes I see before strange NanoVNA H freeze (but not H4), after long time I enable this and run my H ~2-3 hours and no freeze, so I hope all good

Link Time Optimization (LTO) gives GCC the capability of dumping its internal representation (GIMPLE) to disk, so that all the different compilation units that make up a single executable can be optimized as a single module. This expands the scope of inter-procedural optimizations to encompass the whole program (or, rather, everything that is visible at link time).

**Comment by Ho-Ro** [comment]
Last question, why `|=` this can mask a lot of zeros in the sum of `id0` and `id2`?
```c
  uint64_t uid = id1;
  id0+= id2;
  uid|= id0 | (uid<<32);                  // generate unique 64bit ID
```
better, then id1 and id0+id2 do not interfere.
```c
  uint64_t uid = id1;
  uid = (id0 + id2) | (uid<<32);          // generate unique 64bit ID
```

**Comment by Ho-Ro** [comment]
**With LTO** it makes still problems with my -H (HW ver 3.4 w/o SD card). 
Only HW change:
I have added a 32768 Hz clock XTAL to the CPU which gives a working RTC, but I suspect this may not be the cause of the random freezes (a few minutes to ~1 hour after switching on without any activity).

**Without LTO** a random freeze can happen after one or two day idling at a stupid 5V power supply without any USB activities. This is known the issue #26.

**Comment by Ho-Ro** [comment]
And another small improvement, the radix5 encoding requires 64/5 = 12.8 char, your solution cuts the last 4 bits. My change adds the missing bits and aligns correctly for all string sizes.

```diff
--- a/usbcfg.c
+++ b/usbcfg.c
@@ -201,10 +201,10 @@ static const USBDescriptor vcom_strings[] = {
 #ifdef __USB_UID__
 // Use unique serial string generated from MCU id
 #define UID_RADIX                5                 // Radix conversion constant (5 bit, use 0..9 and A..V)
-#define USB_SERIAL_STRING_SIZE  (64 / UID_RADIX)   // Result string size
+#define USB_SERIAL_STRING_SIZE  ((64 + UID_RADIX -1) / UID_RADIX)   // Result string ceil size
 USBDescriptor *getSerialStringDescriptor(void) {
   uint16_t i;
-  uint16_t *buf    = ((uint16_t *)&spi_buffer[ARRAY_COUNT(spi_buffer)]) - USB_SERIAL_STRING_SIZE - 4; // 16 byte align
+  uint16_t *buf    = ((uint16_t *)&spi_buffer[ARRAY_COUNT(spi_buffer)]) - ((USB_SERIAL_STRING_SIZE + 3) & ~3); // 32 bit align
   USBDescriptor *d = ((USBDescriptor *)buf) - 1;
   uint32_t id0 = *(uint32_t *)0x1FFFF7AC; // MCU id0 address
   uint32_t id1 = *(uint32_t *)0x1FFFF7B0; // MCU id1 address
```

**Comment by Ho-Ro** [comment]
@DiSlord What is your opinion on my last suggestion? I will then also adjust my [PR for the tinySA](https://github.com/erikkaashoek/tinySA/pull/112) accordingly.

**Pull request closed without merging**
