### PR TITLE
Restructure NanoVNA repo

### PR DESCRIPTION
**Pull request by Ho-Ro**
Hello DiSlord,
I replaced the submodule ChibiOS with inlined code that makes it easier to maintain and fix. As the NanoVNA FW already uses a special older version it doesn't make sense (IMHO) to use a submodule that needs some fixes anyhow to be able to build the project.
I did this step by step to make it as transparent as possible:
1. remove the submodule ChibiOS
2. fetch ChibiOS code
3. apply the changes from #1 to ChibiOS
4. apply the fix for #11
5. apply the fix for #9
6. apply the fix for #10

Please check if you like my contribution. It is also base for some improvements/changes for my need at [my devel branch](https://github.com/Ho-Ro/NanoVNA-D/commits/devel_horo).

Martin

Add: small shell command improvement #14

### CODE REVIEW

**Comment by DiSlord** [comment]
I update code as in this pr
(Can`t apply direct from your pr, i added some changes later and more easy just add my ChibiOS dir in code)

**Comment by Ho-Ro** [comment]
Looks good so far, BUT the file `stm32f0xx.h`cannot be found :(
This is the file `ChibiOS/os/common/ext/CMSIS/ST/STM32F0xx/stm32f0xx.h`, but the directory `ChibiOS/os/common/ext/CMSIS` is missing.
If I link this directory from my ChibiOS structure then all is built perfectly.
And one last remark, please change the comment in usbconfig.h, line 70:
`0x00,          /* bInterfaceProtocol (AT commands,`
from "AT commands" to "No protocol", because 00=No protocol and 01=AT commands

**Comment by DiSlord** [comment]
Upload CMSIS
Add fixes to ChibiOS USB rx/tx buffers (rx not need big and double buffering, for tx need more speed)
Also add align for data in flash, it allow save lot of space

**Comment by Ho-Ro** [comment]
Not at all - I have found a way to improve the Nano for myself, why shouldn't I make that available to others? You do the same, so thank you for that too. 
I like the global approach to how the device has evolved - edy555's idea from Japan is being serialised in China by hugen and you are extending hugen's firmware in Russia, while people around the world, e.g. Rune in Denmark and Joe Q. in the US are contributing PC software, not to mention Gabriel's (OwO) contribution in the form of the HW-forks. And if the discussion sometimes gets a bit polemical, in the end it comes to a common understanding.

**Pull request closed without merging**
